-- At first it looks like this :
SELECT * FROM ETH.ETH_SCHEMA.TOKEN_TRANSFERS
Limit 100 ;
-- And we need to change it to this
select * from DECIDEOM_LYON.ETH_SCHEMA.CONTRACTS limit 40 ;

-- We need to clone contracts table to execute dbt run
create or replace table DECIDEOM_LYON.ETH_SCHEMA.CONTRACTS_CLONE
CLONE DECIDEOM_LYON.ETH_SCHEMA.CONTRACTS ; 

SELECT * 
FROM DECIDEOM_LYON.ETH_SCHEMA.CONTRACTS_CLONE ;

DELETE FROM DECIDEOM_LYON.ETH_SCHEMA.CONTRACTS_CLONE
WHERE BLOCK_NUMBER > 25362147 ;

-- NOTE : DON'T FORGET TO CHANGE DATABASE NAME IN SQL QUERY AND IN TEST_FILES IF CONFIGURATION OR SNOW ENV CHANGE!
CREATE SCHEMA DECIDEOM_LYON.DBT_SNOW_SEEDS ;
DROP SCHEMA DECIDEOM_LYON.DBT_SNOW_DBT_SEEDS ;
SELECT * FROM DECIDEOM_LYON.DBT_SNOW_SEEDS.STABLECOINS ;
-- NOTE : DONT'T FORGET TO RUN DBT SEED command

-- NOTE : Missing role tester 
USE DATABASE decideom_lyon ;
CREATE ROLE TESTER ;

GRANT ROLE TESTER TO USER bbrossillon ; 

USE SECONDARY ROLES NON ; 
