version: 2

models:

  - name: stg_token_transfer
    description: Transactions in the Ethereum blockchain
    columns:
    - name: transaction_hash
      data_tests:
        - relationships:
            arguments:
              to: ref('stg_transactions')
              field: hash

  - name: stg_transactions
    description: Transactions in the Ethereum blockchain
    columns:
    - name: hash
      config: 
        tags: ['keys']
      description: > 
        This is a very long multiline description
        identifier of each transaction
      data_tests:
        - unique
        - not_null
        - relationships:
            arguments:
              to: ref('stg_token_transfer')
              field: transaction_hash
              # Very important to set the severity to warn, otherwise dbt will fail the run if this test fails
              severity: warn
              config:
                store_failures: true
                store_failures_as: table
                where: date > current_date - 25
  

  - name: int_transactions_enriched
    description: Transactions in the Ethereum blockchain, already transforme
    columns:
    - name: value
      description: > 
        This is a very long multiline description
        identifier of each transaction
      data_tests:
        - assert_value_amount_positive:
            arguments:
              #to: 
              field: block_number


  - name: stablecoin_activity_per_day
    latest_version: 1
    description: We are going to applied a contract
    config:
      contract:
        enforced: true
        alias_types: false
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar(150) # dbt does not check the size, precision or scale
        description: ""
        data_tests:
          - accepted_values:
              arguments:
                values: ["Hybrid", "Crypto-backed", "Fiat-backed"]

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""

    versions:
      - v: 1
        # Will match above definition
        deprecation_date: 2026-07-10
      - v: 2
        # We remove two columns 
        columns:
          - include: all
            exclude: [token_address, symbol]


unit_tests:
  - name: test_is_valid_transaction_category_breakdown
    model: int_transactions_enriched
    overrides:
      macros:
        # unit test this model in "full refresh" mode
        is_incremental: false 
    given:
      - input: ref('stg_transactions')
        rows:
          - {receipt_contract_address: 'bla'}
      # unit test depends on this model, so it should be referenced
      - input: ref('stg_token_transfer')
        rows:
          - {transaction_hash: 'bla'}

    expect:
      rows:
        - {transaction_category: 'contract_creation'}
# Unit test only return 0 or 1. Test pass or failed


exposures:
  # Mandatory fields are : name, type, owner
  - name: eth_activity_per_day
    type: dashboard

    depends_on:
      - ref('int_transactions_enriched')

    owner:
      name: BBrossillon
      email: bbrossillon@udemy.com

