version: 2

sources:
  - name: eth
    # quoting:
    #   database: true
    #   schema: true
    description: Sources of the data in the Ethereum
    schema: eth_schema
    tables:
     - name : contracts
       identifier: contracts
       description  : This is my contracts table
     - name : contracts_clone
     - name : token_transfers
       description  : This is my token transfers table
       config:
        freshness: null
     - name : transactions
       identifier: transactions
       columns:
        - name: hash
          description: > 
            This is a very long multiline description
            identifier of each transactiont
          data_tests:
            - unique

